apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: {{ .Values.image.tag }}
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
    tag: {{ .Values.image.tag }}
  type: {{ .Values.service.type }}
  
